[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[[bin]]
name = "migration"
path = "src/main.rs"

[dependencies]
sea-orm = { version = "^0.12" }
sea-orm-migration = { version = "^0.12", features = ["sqlx-postgres", "runtime-tokio-native-tls"] }
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
dotenv = "0.15"
