t-- Modify Users table
ALTER TABLE users
ADD COLUMN role VARCHAR(50) NOT NULL DEFAULT 'user',
ADD COLUMN name VARCHAR(255),
ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN verification_token VARCHAR(255),
ADD COLUMN verification_token_expires TIMESTAMP WITH TIME ZONE,
ADD COLUMN reset_token VARCHAR(255),
ADD COLUMN reset_token_expires TIMESTAMP WITH TIME ZONE,
ADD COLUMN firebase_uid VARCHAR(255);
