//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

pub mod prelude;

pub mod attachments;
pub mod comments;
pub mod notifications;
pub mod project_members;
pub mod projects;
pub mod task_assignments;
pub mod task_dependencies;
pub mod tasks;
pub mod users;
