//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

pub use super::attachments::Entity as Attachments;
pub use super::comments::Entity as Comments;
pub use super::notifications::Entity as Notifications;
pub use super::project_members::Entity as ProjectMembers;
pub use super::projects::Entity as Projects;
pub use super::task_assignments::Entity as TaskAssignments;
pub use super::task_dependencies::Entity as TaskDependencies;
pub use super::tasks::Entity as Tasks;
pub use super::users::Entity as Users;
