//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use super::{project_members, tasks, users};

#[derive(DeriveEntityModel, Clone, Debug, PartialEq, Serialize, Deserialize)]
#[sea_orm(table_name = "projects")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_by: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub start_date: Option<DateTimeWithTimeZone>,
    pub due_date: Option<DateTimeWithTimeZone>,
    pub status: String,  // 'NEW', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELLED'
    pub priority: String, // 'LOW', 'MEDIUM', 'HIGH', 'URGENT'
    #[sea_orm(column_type = "Text", nullable)]
    pub category: Option<String>,
    #[sea_orm(column_type = "Json", nullable)]
    pub metadata: Option<Json>,
    pub visibility: String, // 'PUBLIC', 'PRIVATE', 'TEAM'
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub tags: Option<Vec<String>>,
    pub progress: f32,  // 0-100%
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::project_members::Entity")]
    ProjectMembers,
    #[sea_orm(has_many = "super::tasks::Entity")]
    Tasks,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Users,
}

impl Related<project_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectMembers.def()
    }
}

impl Related<tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tasks.def()
    }
}

impl Related<users::Entity> for Entity {
    fn to() -> RelationDef {
        project_members::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(project_members::Relation::Projects.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
